# Generated by Django 2.0.13 on 2021-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor do pedido')),
                ('data_pedido', models.DateField(auto_now=True)),
            ],
        ),
    ]
