# Generated by Django 3.1.7 on 2021-03-02 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
