# Generated by Django 3.1.7 on 2021-03-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_usuario_senha_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
