# Generated by Django 2.0.13 on 2021-03-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20210303_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Usuario', verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor do pedido'),
        ),
    ]
