# Generated by Django 2.0.13 on 2021-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210320_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(max_length=50, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(max_length=50, verbose_name='Sobrenome'),
        ),
    ]
